### PR TITLE
sdl2 version

### PR DESCRIPTION
**Pull request by midzer**
Hi again,

build fine for me.

I remember we still have to free new `m_pWindow` and `m_pRenderer` on program quit.

Will close https://github.com/bjaraujo/Bombermaaan/issues/53

Cheers
midzer

### CODE REVIEW

**Comment by bjaraujo** [comment]
Hi, I had to add FindSDL2_mixer.cmake to cmake/modules to compile on Linux. 
Maybe it would be better to add FindSDL2.cmake and FindSDL2_net.cmake as well.

**Comment by midzer** [comment]
Yes, I have not tested other OS except debian 11.

**Comment by bjaraujo** [comment]
Also on Windows I get: 
identifier "SDL_DisplayFormat" is undefined	Bombermaaan	E:\Projects\Bombermaaan2\Bombermaaan\trunk\src\CVideoSDL.cpp	519

**Comment by bjaraujo** [comment]
I merged it into sdl2 branch. There are still some issue that need to be fixed such as the F3/F4 keys.

**Comment by bjaraujo** [comment]
This has been merged into master now.

**Comment by midzer** [comment]
Great :)

**Pull request merged**
